import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Suspense, lazy } from "react";
import { Container } from "react-bootstrap";
import DetailPage from "../src/components/DetailPage/DetailPage";
import WhatIs from "../src/components/HomePage/whatissafeelect/WhatIs";
import Layout from "../src/components/Layout/Layout";
import Slider from "../src/components/Slider/Slider";
import styles from "./Home.module.scss";

const Home: NextPage = () => {
  return (
    <Layout>
      <Slider />
      <div className={styles.homePageContainer}>
        <Head>
          <title>Safe Elect</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="http://localhost:3000/images/logo/vote.png" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel={"preconnect"} href="https://fonts.gstatic.com" />
          <link
            href={
              "https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
            }
            rel="stylesheet"
          ></link>
        </Head>

        <Container>
          <WhatIs />
        </Container>

        <main className={styles.main}>
          {/* <h1 className={styles.title}>Main Page</h1> */}
        </main>
      </div>
    </Layout>
  );
};

export default Home;
