import Head from "next/head";
import Layout from "../../src/components/Layout/Layout";
import styles from "../../styles/Home.module.css";
import DetailPage from "../../src/components/DetailPage/DetailPage";
import React from "react";
import styled from "@emotion/styled";


function vote() {
    const Container = styled.div`
        display: flex;
        flex-direction: column;
        width: 80%;
        margin-left: auto;
        margin-right: auto;
        justify-content: center;
        align-items: center;
        padding: 5rem 0rem;
    `;
    const Title = styled.h1`
        display: flex;
        font-weight: bold;
        color: #2256a4;
        border-bottom: 5px solid #2256a4;
    `;

    const Title2 = styled.h2`
        
        display: flex;
        font-weight: bold;
        margin-top:2rem;
    `;

    const Context = styled.p`
        // text-align: center;
        padding: 2rem 0rem;
        border-bottom: 1px solid black;
    `;

    return (
        <>
            <Layout>
                <DetailPage breadCrumbClass="header-height" pageTitle=" ">
                    <div className={styles.homePageContainer}>
                        <Head>
                            <title>Safe Elect</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/vote.png" />
                        </Head>
                        <Container>
                            <Title>
                                About Us
                            </Title>
                            <Title2>
                                What is SafeElect?
                            </Title2>
                            <Context>
                                SafeElect is a Digital Election System that allows its users to create elections and participate in the ongoing elections.
                                SafeElect aims to provide secure, confidential and available elections by using the power of the web and blockchain specifically Binance Smart Chain.
                            </Context>
                            <Title2>
                                Who are we?
                            </Title2>
                            <Context>
                                We are a team called <b>"Tabs &gt; Spaces"</b> which came together to build SafeElect as a final year project. The team has 4 developers who are students at the department of CTIS and Dr. Seyid Amjad Ali as advisor.
                            </Context>
                        </Container>
                    </div>
                </DetailPage>
            </Layout>
        </>
    );
}

export default vote;
