import Head from "next/head";
import Layout from "../../src/components/Layout/Layout";
import styles from "./aboutus.module.scss";
import DetailPage from "../../src/components/DetailPage/DetailPage";
import React from "react";
import styled from "@emotion/styled";
import { Col } from "react-bootstrap";

function Aboutus() {
  const Container = styled.div`
    display: flex;
    flex-direction: column;
    width: 80%;
    margin-left: auto;
    margin-right: auto;
    justify-content: center;
    align-items: center;
    padding: 5rem 0rem;
  `;
  const Title = styled.h1`
    display: flex;
    font-weight: bold;
    color: #2256a4;
    border-bottom: 5px solid #2256a4;
  `;

  const Title2 = styled.h2`
    display: flex;
    font-weight: bold;
    margin-top: 2rem;
  `;

  const Context = styled.p`
    // text-align: center;
    padding: 2rem 0rem;
    border-bottom: 1px solid black;
  `;

  return (
    <>
      <Layout>
        <DetailPage breadCrumbClass="header-height" pageTitle=" ">
          <div className={styles.aboutUsContainer}>
            <Head>
              <title>Safe Elect</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/vote.png" />
            </Head>
            <Container className="text-center">
              <Col xl={{ span: 4 }} >
                <h2>About Us</h2>
                <br />
                <br />
              </Col>

              <Col xl={{span:4}}>
                <h3>What is SafeElect?</h3>
                <h5>
                  SafeElect is a Digital Election System that allows its users
                  to create elections and participate in the ongoing elections.
                  SafeElect aims to provide secure, confidential and available
                  elections by using the power of the web and blockchain
                  specifically Binance Smart Chain.
                </h5>
              </Col>
              <br />
              <br />
              <Col xl={{span:4}}>
                <h3>Who are we?</h3>
                <h5>
                We are a team called <b>Tabs &gt; Spaces</b> which came together
                to build SafeElect as a final year project. The team has 4
                developers who are students at the department of CTIS and Dr.
                Seyid Amjad Ali as advisor.
                </h5>
              </Col>
            </Container>
          </div>
        </DetailPage>
      </Layout>
    </>
  );
}

export default Aboutus;
